sudo: true
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache:
  directories:
    - node_modules
install:
  - npm install
branches:
  only:
    - dev
before_script:
  - chmod 0777 ./node_modules/.bin/hexo
script:
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: $P_BRANCH
  on:
    branch: dev
  local-dir: public
