dist: bionic
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache:
  directories:
    - node_modules
before_install:
  - wget http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.30-0ubuntu2_amd64.deb
  - sudo dpkg -i --auto-deconfigure libc6_2.30-0ubuntu2_amd64.deb
install:
  - npm install
branches:
  only:
    - dev
before_script:
  - chmod 0777 ./node_modules/.bin/hexo
script:
  - hexo generate
deploy:
  provider: pages
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: $P_BRANCH
  on:
    branch: dev
  local-dir: public
