sudo: true
dist: bionic
language: node_js
cache: false
node_js:
  - lts/*
install:
  - npm install dart-sass
  - npm install
branches:
  only:
    - dev
before_script:
  - echo "Starting to generate html ..."
script:
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: false
  target_branch: $P_BRANCH
  on:
    branch: dev
  local-dir: public
