sudo: true
dist: bionic
language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
install:
  - LIBSASS_EXT="no" npm install
  - npm rebuild node-sass
branches:
  only:
    - dev
before_script:
  - chmod 777 ./node_modules/.bin/hexo
script:
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: $P_BRANCH
  on:
    branch: dev
  local-dir: public
